/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

/**
 *
 * @author Prasad
 */
public class CustomerQueuePanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerQueuePanel
     */
    public CustomerQueuePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_addCus = new javax.swing.JButton();
        btn_RefreshCus = new javax.swing.JButton();
        dlt_cus = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "CustomerID", "ParcelID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 303, 340));

        btn_addCus.setText("ADD");
        btn_addCus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addCusActionPerformed(evt);
            }
        });
        add(btn_addCus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        btn_RefreshCus.setText("Refresh");
        btn_RefreshCus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RefreshCusActionPerformed(evt);
            }
        });
        add(btn_RefreshCus, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, -1, -1));

        dlt_cus.setText("Delete");
        dlt_cus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dlt_cusActionPerformed(evt);
            }
        });
        add(dlt_cus, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addCusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addCusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_addCusActionPerformed

    private void dlt_cusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dlt_cusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dlt_cusActionPerformed

    private void btn_RefreshCusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RefreshCusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_RefreshCusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_RefreshCus;
    private javax.swing.JButton btn_addCus;
    private javax.swing.JButton dlt_cus;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
