/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Prasad
 */
public class ParcelsToProcessPanel extends javax.swing.JPanel {

    /**
     * Creates new form ParcelsToProcessPanel
     */
    public ParcelsToProcessPanel() {
        loadDataToTable();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_parcel = new javax.swing.JTable();
        btn_addParcel = new javax.swing.JButton();
        btn_refresh = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_parcel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ParcelID", "Days in Depot", "Weight", "Lenght", "Width", "Height", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_parcel);
        if (tbl_parcel.getColumnModel().getColumnCount() > 0) {
            tbl_parcel.getColumnModel().getColumn(0).setResizable(false);
            tbl_parcel.getColumnModel().getColumn(1).setResizable(false);
            tbl_parcel.getColumnModel().getColumn(2).setResizable(false);
            tbl_parcel.getColumnModel().getColumn(3).setResizable(false);
            tbl_parcel.getColumnModel().getColumn(4).setResizable(false);
            tbl_parcel.getColumnModel().getColumn(5).setResizable(false);
            tbl_parcel.getColumnModel().getColumn(6).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 460, 336));

        btn_addParcel.setText("ADD Parcels");
        btn_addParcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addParcelActionPerformed(evt);
            }
        });
        add(btn_addParcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        btn_refresh.setText("Refersh");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });
        add(btn_refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addParcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addParcelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_addParcelActionPerformed

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_refreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addParcel;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_parcel;
    // End of variables declaration//GEN-END:variables
   
    public void loadDataToTable(){
       String filePath = "Parcels.csv";  // Path to the CSV file
       DefaultTableModel model = (DefaultTableModel) tbl_parcel.getModel();

    // Clear existing rows in the table
    model.setRowCount(0);

    try (BufferedReader br = new BufferedReader(new FileReader(filePath))) {
        String line;
        while ((line = br.readLine()) != null) {
            String[] values = line.split(",");  // Split the line by commas

            // Check if parcel is marked as collected
            String status = (values.length > 6 && values[6].equalsIgnoreCase("Collected")) ? "Collected" : "Pending";

            // Add row to table with parcel details and status
            model.addRow(new Object[] {
                values[0],  // Parcel ID
                values[1],  // Length
                values[2],  // Width
                values[3],  // Height
                values[4],  // Weight
                values[5],  // Days in Depot
                status      // Status (Pending or Collected)
            });
        }
    } catch (IOException e) {
        System.out.println("Error loading data: " + e.getMessage());
    }
    
    }

}
